services:
  bahninfo:
    image: niggiover9000/easy_redirect:latest
    container_name: easy-redirect
    restart: always
    ports:
      - 5000:5000
    networks:
      - "proxy"
    volumes:
      - .env:/app/.env